language: android

before_script:
  - sudo service mysql stop || true
  - sudo service postgresql stop || true
  - sudo service mongodb stop ||
  - sudo service --status-all

android:
  components:
    - tools
    - build-tools-23.0.2
    - android-23
    - extra-android-m2repository
